# Generated by Django 2.0.13 on 2020-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField()),
                ('title', models.TextField()),
                ('h1', models.SmallIntegerField()),
                ('s1', models.SmallIntegerField()),
                ('v1', models.SmallIntegerField()),
                ('h2', models.SmallIntegerField()),
                ('s2', models.SmallIntegerField()),
                ('v2', models.SmallIntegerField()),
                ('h3', models.SmallIntegerField()),
                ('s3', models.SmallIntegerField()),
                ('v3', models.SmallIntegerField()),
                ('imageurl', models.TextField()),
            ],
        ),
    ]
