# Generated by Django 3.0.8 on 2020-10-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200927_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
