# Generated by Django 3.1.2 on 2020-11-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='image',
            name='imgpath',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
