# Generated by Django 3.1.2 on 2020-11-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20201126_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imgpath',
        ),
    ]
